localResource check if HtmlFile
The hrefs need to be valid html links and we should check the regex before processing the file. Noticed this when processing pages containing javacript scripts href=javascript:show(id) for example, this gives the following error :
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [class java.lang.String, null] due to overlapping prototypes between:
    [class java.lang.String, class java.lang.String]
    [class java.lang.String, class java.io.File]